Algoritmo "Concatenação"
// 
//  
// Descrição   : Concatenação
// Autor(a)    : Angelo
// Data atual  : 24/09/2024
Var
// Seção de Declarações das variáveis 
   nome : caractere
     numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreval ("Digite o nome:")
  Leia (nome)
  escreval ("Digite o numero:")
  Leia (numero)
  
  escreval (nome, " : ", numero)

Fimalgoritmo