Algoritmo "Meu primeiro algoritmo"
//  Disciplina : [Linguagem e lógica da programação]
//  Professor  : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Angelo Henrique Martins Dias
// Data atual  : 17/09/2024
Var
// Seção de Declarações das variáveis 
  nota : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     nota <- 100
    Escreva ("Resultado:", nota)
     
Fimalgoritmo